id: P007121
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4458
  title: རྡོ་རྗེ་ནག་པོ་ཕྱག་བཞི་པའི་ཕྱི་ནང་གསང་གསུམ་གྱི་འཁོར་ལོའི་བྲི་ཐབས་གསལ་བྱེད་བླ་མའི་ཕྱག་ལེན་
  author: ''
  volumes:
    62df52d803474be3b781d27eb6ebfc94:
      image_group_id: I1KG4580
      title: ''
      volume_number: 1
      total_pages: 62
ebook_metadata:
  title: རྡོ་རྗེ་ནག་པོ་ཕྱག་བཞི་པའི་ཕྱི་ནང་གསང་གསུམ་གྱི་འཁོར་ལོའི་བྲི་ཐབས་གསལ་བྱེད་བླ་མའི་ཕྱག་ལེན་
  author: ''
  sku: P007121
  cover: cover.jpg
  layers:
  - pagination
