id: opecha:P007121
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4458
  title: རྡོ་རྗེ་ནག་པོ་ཕྱག་བཞི་པའི་ཕྱི་ནང་གསང་གསུམ་གྱི་འཁོར་ལོའི་བྲི་ཐབས་གསལ་བྱེད་བླ་མའི་ཕྱག་ལེན་
  volume: ''
  author: ''
